name: CM4 Image Build Automation

on:
  push:
    branches: [ "next" ]
  workflow_dispatch:

jobs:
  build_opi-cm4:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: build script
      run: sudo CONFIG="${{ github.workspace }}/external/config/config-opicm4.conf" ./build.sh
    # - uses: actions/upload-artifact@v4
